sudo: required

services:
  - docker

before_install:
  - docker pull jekyll/jekyll:pages

script:
  - docker run --rm -v $PWD:/srv/jekyll jekyll/jekyll:pages sh -c "bundle install && jekyll build && bundle exec htmlproof ./_site"
