# Jekyll + Travis with Docker not work well - [Error:  Permission denied](https://travis-ci.org/ibotdotout/ibotdotout.github.io/builds/81637869)
# Travis support docker but not fully permission some dependencies that
# try to use OS command ex. kill can make your test error or failed.

sudo: false

language: ruby

rvm:
  - 2.2

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --disable-external

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
