sudo: false
language: ruby
rvm:
- 2.2

branches:
  only:
  - develop

script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --disable-external

# deploy from devlope bramch to master branch and update index.json for searching
after_success:
- git clone https://$GH_REF
- cd $(basename ${GH_REF%.git})
- git pull origin develop
- cp ../_site/js/index.json js/index.json
- git config user.name "Travis-CI"
- git config user.email "deploy@travis.com"
- git commit -am "Generated index.json by Travis CI"
- git push -f "https://${DEPLOY_KEY}@${GH_REF}" master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/ibotdotout/ibotdotout.github.io.git
  - secure: XhG0/MZjThMYdlosJkfRr8wpZLSxuXKf4i/jbuDrhkbwI4aIe46aYKkm3L6TaTYXXYjb8o2begoPKVE9TPTBu6goL5Pjl4TSLf0ARH/Q6Ue6Ukub3G81EF29H+XhV9y/yAWrfHpsk/a0Q3aMX8+EgUDKrdIfvZAZZXJ/puR/POw=
