# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            botbotbot
tagline:          "'s blog"
description:      "botbotbot's blog"
locale:           th_TH
url:              http://dev.im-bot.com
logo:             /public/opengraph_logo.png
paginate:         5
baseurl: /

author:
  name:           botbotbot
  avatar:         https://avatars0.githubusercontent.com/u/686676?v=3&s=460
  url:            http://dev.im-bot.com

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/ibotdotout

google_analytics_id: UA-52133577-1

gems:
    - jekyll-feed
