# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: rouge
# highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            botbotbot
tagline:          "'s blog"
description:      "botbotbot's blog"
locale:           th_TH
url:              http://dev.im-bot.com
logo:             /public/opengraph_logo.png
paginate:         5
baseurl: /

date_format: '%B %d, %Y'

disqus_shortname: 'im-bot'
comment: true

excerpt_separator: <!-- more -->

author:
  name:           botbotbot
  avatar:         https://avatars0.githubusercontent.com/u/686676?v=3&s=460
  url:            http://dev.im-bot.com

# Prevent File/Dir publish to site
exclude: [Dockerfile, Gemfile, Gemfile.lock, LICENSE.md, docker-compose.yml, vendor]

# Jekyll Plugins
# gems:
gems:           
    - jekyll-paginate
    - jekyll-gist
    - redcarpet
    - jekyll-feed
    - jekyll-lunr-js-search
    - octopress-minify-html

# Plugins config
lunr_search:
    excludes: [feed.xml, tags, search, "404"]

minify_html: true

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/ibotdotout

google_analytics_id: UA-52133577-1

