# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            botbotbot
tagline:          "'s blog"
description:      "botbotbot's blog"
locale:           th_TH
url:              http://ibotdotout.github.io
paginate:         5
baseurl: /


author:
  name:           botbotbot
  url:            http://ibotdotout.github.io

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/ibotdotout
